### ISSUE TITLE
Get rid of dynamic_cast

### ISSUE THREAD

**Issue by dschwen** [dschwen/mathparse#21]
dynamic_cast requires RTTI and ssems to cause problems when mixing clang and libgccjit. Also if LLVM is configured without RTTI it will set `-fno-rtti` as a compiler parameter in `llvm-config`.
I think we can do without `dynamic_cast`, which is needed to compare value providers in the differentiation algorithm. I'm only ever testing if the class types are the _exact_same, so I could roll my own simple typeid scheme. The challenge is generating the typeids. They cannot be `static int typeid++` type of ids - those don't reliably work with dynamic linking. They cannot be predefined enum entries, because I want to allow custom value providers.

**Comment by dschwen** [comment]
This does the trick:

```
#include <iostream>

/////////

class Base
{
public:
  bool sameAs(Base * a) { return getTypeID() == a->getTypeID(); }

protected:
  virtual void * getTypeID() = 0;
};

template <class T>
class TypeInfo : public Base
{
public:
protected:
  TypeInfo() { (void)_typeinfo_tag; }
  virtual void * getTypeID() { return reinterpret_cast<void *>(&_typeinfo_tag); };

private:
  static int _typeinfo_tag;
};

template <class T>
int TypeInfo<T>::_typeinfo_tag;

/////////

class Derived1 : public TypeInfo<Derived1>
{
};

class Derived2 : public TypeInfo<Derived2>
{
};

int
main()
{
  Base * A = new Derived1;
  Base * B = new Derived1;
  Base * C = new Derived2;
  Base * D = new Derived2;

  std::cout << "A->sameAs(A) = " << A->sameAs(A) << '\n';
  std::cout << "A->sameAs(B) = " << A->sameAs(B) << '\n';
  std::cout << "A->sameAs(C) = " << A->sameAs(C) << '\n';
  std::cout << "C->sameAs(D) = " << C->sameAs(D) << '\n';
  std::cout << "D->sameAs(D) = " << D->sameAs(D) << '\n';
  std::cout << "D->sameAs(A) = " << D->sameAs(A) << '\n';
  return 0;
}
```

It looks a bit insane to have a class inherit from a template with the class itself as an argument, but it works. The typeid is the address of the template- (and thus class-) specific static member.

**Comment by dschwen** [comment]
Hey @roystgnr, @permcody suggested to ask you for input on this (he mentioned that you have experience with RTTI and how to avoid using it).

**Comment by roystgnr** [comment]
> It looks a bit insane to have a class inherit from a template with the class itself as an argument, but it works.

It's called the [Curiously Recurring Template Pattern](https://en.wikipedia.org/wiki/Curiously_recurring_template_pattern) and it was the most confusing C++ism I'd ever seen when I first encountered it, but it's useful and popular.  libMesh uses it for ReferenceCountedObject and safe_bool subclasses.

> you have experience with RTTI and how to avoid using it

Just a little.  libMesh has with- and without-RTTI paths in cast_ptr and cast_ref, but those are only for cases where you shouldn't really *need* RTTI, it's just useful as an assertion to make sure users aren't trying to mix incompatible subclasses of e.g. linear algebra types.

If I'd been in your shoes then I'd have created a static void function and compared function pointers, but I don't think that's possible header-only.  The cast from a static member address to a void pointer looks even uglier but ought to work better.
